# Use the official lightweight Node.js 12 image.
# https://hub.docker.com/_/node
FROM node:8.16.2-jessie-slim

ARG ENVIRONMENT=development
# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying this separately prevents re-running npm install on every code change.
COPY package*.json ./

# Install production dependencies.
RUN npm i


# Copy local code to the container image.
COPY . ./
RUN echo $(ENVIRONMENT)
RUN npm run build

RUN npm run test:mocha

EXPOSE 8080
# Run the web service on container startup.
CMD [ "ENVIRONMENT=$(ENVIRONMENT)", "npm", "run", "express:???" ]